[package]
name = "rbytepair"
version = "0.1.0"
authors = ["KeironO <keiron.oshea@gmail.com>"]
edition = "2018"

[dependencies]
pyo3 = { version = "0.7.0", features = ["extension-module"] }

[lib]
name = "rbytepair"
crate-type = ["cdylib"]
